config/routes.rb
Rails.application.routes.draw do
  get 'activities/index'

  resources :click_frequencies

  resources :measurements

  resources :measure_units

  resources :measure_names

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'activities#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/measure_name.rb
class MeasureName < ActiveRecord::Base
  belongs_to :measurement
  has_many :click_frequencies
end

app/controllers/measure_names_controller.rb
class MeasureNamesController < ApplicationController
  before_action :set_measure_name, only: [:show, :edit, :update, :destroy]

  # GET /measure_names
  # GET /measure_names.json
  def index
    @measure_names = MeasureName.all
  end

  # GET /measure_names/1
  # GET /measure_names/1.json
  def show
  end

  # GET /measure_names/new
  def new
    @measure_name = MeasureName.new
  end

  # GET /measure_names/1/edit
  def edit
  end

  # POST /measure_names
  # POST /measure_names.json
  def create
    @measure_name = MeasureName.new(measure_name_params)

    respond_to do |format|
      if @measure_name.save
        format.html { redirect_to @measure_name, notice: 'Measure name was successfully created.' }
        format.json { render :show, status: :created, location: @measure_name }
      else
        format.html { render :new }
        format.json { render json: @measure_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measure_names/1
  # PATCH/PUT /measure_names/1.json
  def update
    respond_to do |format|
      if @measure_name.update(measure_name_params)
        format.html { redirect_to @measure_name, notice: 'Measure name was successfully updated.' }
        format.json { render :show, status: :ok, location: @measure_name }
      else
        format.html { render :edit }
        format.json { render json: @measure_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measure_names/1
  # DELETE /measure_names/1.json
  def destroy
    @measure_name.destroy
    respond_to do |format|
      format.html { redirect_to measure_names_url, notice: 'Measure name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measure_name
      @measure_name = MeasureName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measure_name_params
      params.require(:measure_name).permit(:name, :measurement_id, :position)
    end
end

app/helpers/measure_names_helper.rb
module MeasureNamesHelper
end

app/views/measure_names/_form.html.erb
<%= form_for @measure_name, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :position, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :position, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  measure_names_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/measure_names/edit.html.erb
<%- model_class = MeasureName -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => MeasureName %></h1>
</div>
<%= render :partial => 'form' %>

app/views/measure_names/index.html.erb
<%- model_class = MeasureName -%>
<div class="page-header">
  <h1><%=t '.title', :default => MeasureName %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @measure_names.each do |measure_name| %>
      <tr>
        <td><%= measure_name.id %></td>
        <td><%= measure_name.name %></td>
        <td><%= measure_name.position %></td>
        <td><%=l measure_name.created_at, format: :long %></td>
        <td>
          <%= link_to measure_name_path(measure_name), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to measure_name_path(measure_name), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_measure_name_path,
            :class => 'btn btn-primary' %>

app/views/measure_names/new.html.erb
<%- model_class = MeasureName -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => MeasureName %></h1>
</div>
<%= render :partial => 'form' %>

app/views/measure_names/show.html.erb
<%- model_class = MeasureName -%>
<div class="page-header">
  <h1><%=t '.title', :default => MeasureName %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @measure_name.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:position) %></dt>
      <dd><pre class="prettyprint"><%= @measure_name.position %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              measure_names_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_measure_name_path(@measure_name), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              measure_name_path(@measure_name),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>