config/routes.rb
Rails.application.routes.draw do
  get 'activities/index'

  resources :click_frequencies

  resources :measurements

  resources :measure_units

  resources :measure_names

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'activities#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/click_frequency.rb
class ClickFrequency < ActiveRecord::Base
  belongs_to :user
  belongs_to :measure_name
end

app/controllers/click_frequencies_controller.rb
class ClickFrequenciesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_click_frequency, only: [:show, :edit, :update, :destroy]

  # GET /click_frequencies
  # GET /click_frequencies.json
  def index
    @click_frequencies = ClickFrequency.all
  end

  # GET /click_frequencies/1
  # GET /click_frequencies/1.json
  def show
  end

  # GET /click_frequencies/new
  def new
    @click_frequency = ClickFrequency.new
  end

  # GET /click_frequencies/1/edit
  def edit
  end

  # POST /click_frequencies
  # POST /click_frequencies.json
  def create
    @click_frequency = ClickFrequency.new(click_frequency_params)
    @click_frequency.user = current_user

    respond_to do |format|
      if @click_frequency.save
        format.html { redirect_to @click_frequency, notice: 'Click frequency was successfully created.' }
        format.json { render :show, status: :created, location: @click_frequency }
      else
        format.html { render :new }
        format.json { render json: @click_frequency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /click_frequencies/1
  # PATCH/PUT /click_frequencies/1.json
  def update
    respond_to do |format|
      if @click_frequency.update(click_frequency_params)
        format.html { redirect_to @click_frequency, notice: 'Click frequency was successfully updated.' }
        format.json { render :show, status: :ok, location: @click_frequency }
      else
        format.html { render :edit }
        format.json { render json: @click_frequency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /click_frequencies/1
  # DELETE /click_frequencies/1.json
  def destroy
    @click_frequency.destroy
    respond_to do |format|
      format.html { redirect_to click_frequencies_url, notice: 'Click frequency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_click_frequency
      @click_frequency = ClickFrequency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def click_frequency_params
      params.require(:click_frequency).permit(:count, :user_id, :measure_name_id)
    end
end

app/helpers/click_frequencies_helper.rb
module ClickFrequenciesHelper
end

app/views/click_frequencies/_form.html.erb
<%= form_for @click_frequency, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :count, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :count, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  click_frequencies_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/click_frequencies/edit.html.erb
<%- model_class = ClickFrequency -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => ClickFrequency %></h1>
</div>
<%= render :partial => 'form' %>

app/views/click_frequencies/index.html.erb
<%- model_class = ClickFrequency -%>
<div class="page-header">
  <h1><%=t '.title', :default => ClickFrequency %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:count) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @click_frequencies.each do |click_frequency| %>
      <tr>
        <td><%= click_frequency.id %></td>
        <td><%= click_frequency.count %></td>
        <td><%=l click_frequency.created_at, format: :long %></td>
        <td>
          <%= link_to click_frequency_path(click_frequency), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to click_frequency_path(click_frequency), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_click_frequency_path,
            :class => 'btn btn-primary' %>

app/views/click_frequencies/new.html.erb
<%- model_class = ClickFrequency -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => ClickFrequency %></h1>
</div>
<%= render :partial => 'form' %>

app/views/click_frequencies/show.html.erb
<%- model_class = ClickFrequency -%>
<div class="page-header">
  <h1><%=t '.title', :default => ClickFrequency %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:count) %></dt>
      <dd><pre class="prettyprint"><%= @click_frequency.count %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              click_frequencies_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_click_frequency_path(@click_frequency), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              click_frequency_path(@click_frequency),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>