config/routes.rb
Rails.application.routes.draw do
  get 'activities/index'

  resources :click_frequencies

  resources :measurements

  resources :measure_units

  resources :measure_names

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'activities#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
  belongs_to :user
  has_one :measure_name
  has_one :measure_unit
end

app/controllers/measurements_controller.rb
class MeasurementsController < ApplicationController
  before_action :set_measurement, only: [:show, :edit, :update, :destroy]

  # GET /measurements
  # GET /measurements.json
  def index
    @measurements = Measurement.all
  end

  # GET /measurements/1
  # GET /measurements/1.json
  def show
  end

  # GET /measurements/new
  def new
    @measurement = Measurement.new
  end

  # GET /measurements/1/edit
  def edit
  end

  # POST /measurements
  # POST /measurements.json
  def create
    @measurement = Measurement.new(measurement_params)

    respond_to do |format|
      if @measurement.save
        format.html { redirect_to @measurement, notice: 'Measurement was successfully created.' }
        format.json { render :show, status: :created, location: @measurement }
      else
        format.html { render :new }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measurements/1
  # PATCH/PUT /measurements/1.json
  def update
    respond_to do |format|
      if @measurement.update(measurement_params)
        format.html { redirect_to @measurement, notice: 'Measurement was successfully updated.' }
        format.json { render :show, status: :ok, location: @measurement }
      else
        format.html { render :edit }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurements/1
  # DELETE /measurements/1.json
  def destroy
    @measurement.destroy
    respond_to do |format|
      format.html { redirect_to measurements_url, notice: 'Measurement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measurement
      @measurement = Measurement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measurement_params
      params.require(:measurement).permit(:altitude, :latitude, :longitude, :happened_at, :user_id, :position, :value)
    end
end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/views/measurements/_form.html.erb
<%= form_for @measurement, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :altitude, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :altitude, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :latitude, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :latitude, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longitude, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :longitude, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :happened_at, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :happened_at, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :position, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :position, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :value, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :value, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  measurements_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/measurements/edit.html.erb
<%- model_class = Measurement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Measurement %></h1>
</div>
<%= render :partial => 'form' %>

app/views/measurements/index.html.erb
<%- model_class = Measurement -%>
<div class="page-header">
  <h1><%=t '.title', :default => Measurement %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:altitude) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:happened_at) %></th>
      <th><%= model_class.human_attribute_name(:position) %></th>
      <th><%= model_class.human_attribute_name(:value) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @measurements.each do |measurement| %>
      <tr>
        <td><%= measurement.id %></td>
        <td><%= measurement.altitude %></td>
        <td><%= measurement.latitude %></td>
        <td><%= measurement.longitude %></td>
        <td><%= measurement.happened_at %></td>
        <td><%= measurement.position %></td>
        <td><%= measurement.value %></td>
        <td><%=l measurement.created_at, format: :long %></td>
        <td>
          <%= link_to measurement_path(measurement), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to measurement_path(measurement), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_measurement_path,
            :class => 'btn btn-primary' %>

app/views/measurements/new.html.erb
<%- model_class = Measurement -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Measurement %></h1>
</div>
<%= render :partial => 'form' %>

app/views/measurements/show.html.erb
<%- model_class = Measurement -%>
<div class="page-header">
  <h1><%=t '.title', :default => Measurement %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:altitude) %></dt>
      <dd><pre class="prettyprint"><%= @measurement.altitude %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:latitude) %></dt>
      <dd><pre class="prettyprint"><%= @measurement.latitude %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:longitude) %></dt>
      <dd><pre class="prettyprint"><%= @measurement.longitude %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:happened_at) %></dt>
      <dd><pre class="prettyprint"><%= @measurement.happened_at %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:position) %></dt>
      <dd><pre class="prettyprint"><%= @measurement.position %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:value) %></dt>
      <dd><pre class="prettyprint"><%= @measurement.value %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              measurements_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_measurement_path(@measurement), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              measurement_path(@measurement),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>