config/routes.rb
Rails.application.routes.draw do
  get 'activities/index'

  resources :click_frequencies

  resources :measurements

  resources :measure_units

  resources :measure_names

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords", omniauth_callbacks: "users/omniauth_callbacks"}, skip: [:sessions, :registrations]

  root 'activities#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/measure_unit.rb
class MeasureUnit < ActiveRecord::Base
  belongs_to :measurement
end

app/controllers/measure_units_controller.rb
class MeasureUnitsController < ApplicationController
  before_action :set_measure_unit, only: [:show, :edit, :update, :destroy]

  # GET /measure_units
  # GET /measure_units.json
  def index
    @measure_units = MeasureUnit.all
  end

  # GET /measure_units/1
  # GET /measure_units/1.json
  def show
  end

  # GET /measure_units/new
  def new
    @measure_unit = MeasureUnit.new
  end

  # GET /measure_units/1/edit
  def edit
  end

  # POST /measure_units
  # POST /measure_units.json
  def create
    @measure_unit = MeasureUnit.new(measure_unit_params)

    respond_to do |format|
      if @measure_unit.save
        format.html { redirect_to @measure_unit, notice: 'Measure unit was successfully created.' }
        format.json { render :show, status: :created, location: @measure_unit }
      else
        format.html { render :new }
        format.json { render json: @measure_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measure_units/1
  # PATCH/PUT /measure_units/1.json
  def update
    respond_to do |format|
      if @measure_unit.update(measure_unit_params)
        format.html { redirect_to @measure_unit, notice: 'Measure unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @measure_unit }
      else
        format.html { render :edit }
        format.json { render json: @measure_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measure_units/1
  # DELETE /measure_units/1.json
  def destroy
    @measure_unit.destroy
    respond_to do |format|
      format.html { redirect_to measure_units_url, notice: 'Measure unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measure_unit
      @measure_unit = MeasureUnit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measure_unit_params
      params.require(:measure_unit).permit(:name, :abbreviation, :measurement_id)
    end
end

app/helpers/measure_units_helper.rb
module MeasureUnitsHelper
end

app/views/measure_units/_form.html.erb
<%= form_for @measure_unit, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :abbreviation, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :abbreviation, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  measure_units_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/measure_units/edit.html.erb
<%- model_class = MeasureUnit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => MeasureUnit %></h1>
</div>
<%= render :partial => 'form' %>

app/views/measure_units/index.html.erb
<%- model_class = MeasureUnit -%>
<div class="page-header">
  <h1><%=t '.title', :default => MeasureUnit %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:abbreviation) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @measure_units.each do |measure_unit| %>
      <tr>
        <td><%= measure_unit.id %></td>
        <td><%= measure_unit.name %></td>
        <td><%= measure_unit.abbreviation %></td>
        <td><%=l measure_unit.created_at, format: :long %></td>
        <td>
          <%= link_to measure_unit_path(measure_unit), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to measure_unit_path(measure_unit), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_measure_unit_path,
            :class => 'btn btn-primary' %>

app/views/measure_units/new.html.erb
<%- model_class = MeasureUnit -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => MeasureUnit %></h1>
</div>
<%= render :partial => 'form' %>

app/views/measure_units/show.html.erb
<%- model_class = MeasureUnit -%>
<div class="page-header">
  <h1><%=t '.title', :default => MeasureUnit %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @measure_unit.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:abbreviation) %></dt>
      <dd><pre class="prettyprint"><%= @measure_unit.abbreviation %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              measure_units_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_measure_unit_path(@measure_unit), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              measure_unit_path(@measure_unit),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>